#Digitális Id\u0151mér\u0151 - Konfiguráció
#Thu Dec 11 09:32:41 CET 2025
data.auto.cleanup=false
data.retention.days=90
export.default.format=CSV
export.include.charts=true
monitor.idle.threshold.minutes=5
monitor.interval.ms=2000
stats.daily.target.hours=8
stats.top.apps.limit=10
ui.autostart=false
ui.minimize.to.tray=true
ui.show.notifications=true
ui.update.interval.seconds=1
